# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python package

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  PROJECT_ID: ${{ secrets.DEMO_PROJECT }}
  SERVICE_NAME: trilogy-public-models
  REGION: us-central1

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10",]

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      # Setup gcloud CLI
      - uses: 'actions/checkout@v3'
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1

      # Configure Workload Identity Federation and generate an access token.
      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v1'
        with:
          #https://iam.googleapis.com/projects/230483776791/locations/global/workloadIdentityPools/demo-pool/providers/github-ci
          workload_identity_provider: 'projects/230483776791/locations/global/workloadIdentityPools/demo-pool/providers/github-ci2'
          service_account: '${{ secrets.DEPLOYER_EMAIL }}'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install wheel
          pip install codecov
          pip install -r requirements.txt
          pip install -r requirements-test.txt
      - name: Lint with flake8
        run: |
          pip install flake8
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      - name: Test with pytest
        run: |
          pip install pytest
          pip install pytest-cov
          pytest --ignore=docs_src/ --cov=./
          codecov --token=${{ secrets.CODECOV_TOKEN }}
